name: publish

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
          cache: 'gradle'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build files
        run: ./gradlew build

      - name: read mod name, mod version and minecraft version
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version'

      - name: Do something with your bumped release version
        run: echo ${{ steps.properties.outputs.archives_base_name }}
      - name: Do something with your bumped release version
        run: echo ${{ steps.properties.outputs.mod_version }}
  # will print "the value of 'the.key.of.a.property'"
