name: publish

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: read mod name
        id: mod_name
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: "./gradle.properties"
          property: archives_base_name

      - name: read mod version
        id: mod_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: "./gradle.properties"
          property: mod_version

      - name: read minecraft version
        id: minecraft_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: "./gradle.properties"
          property: minecraft_version

      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
          cache: 'gradle'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build files
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-featured: true
          modrinth-unfeature-mode: subset

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: '${{ steps.mod_name.outputs.value }}-${{ steps.mod_version.outputs.value }}+${{ steps.minecraft_version.outputs.value }}'

          version-type: release
          version: '${{ steps.mod_version.outputs.value }}+${{ steps.minecraft_version.outputs.value }}'
          game-versions: |
            ${{ steps.minecraft_version.outputs.value }}
          version-resolver: exact

          dependencies: |
            cloth-config | depends | *

          changelog-file: CHANGELOG.md

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail