name: Publish

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
          cache: 'gradle'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build files
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          version-type: release
          changelog-file: CHANGELOG.md

          version-resolver: exact

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail