name: test

on:
  workflow_dispatch

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: read mod name, mod version and minecraft version
      id: properties
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './gradle.properties'
        properties: 'archives_base_name mod_version minecraft_version'

    - name: discord webhook
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        filename: CHANGELOG.md
        embed-title: "${{ steps.properties.outputs.archives_base_name }} ${{ steps.properties.outputs.mod_version }} for Minecraft ${{ steps.properties.outputs.minecraft_version }} has been released!"
        embed-color: 0xFF8000